name: Lint

# on:
#   push:
#     branches:
#       - main
on: push

jobs:
# shellcheck:
#   runs-on: ubuntu-latest
#   steps:
#     - uses: actions/checkout@v2
#
#     - name: Run shellcheck
#       uses: ludeeus/action-shellcheck@master
#       env:
#         SHELLCHECK_OPTS: --external-sources

  plugin_test:
    strategy:
      matrix:
        os:
        # - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      # ~/.asdf/bin/asdf plugin-test openresty https://github.com/HaloGithub/asdf-openresty --asdf-tool-version latest --asdf-plugin-gitref 698d27e81d4db30287e90d3c9358029d4bc277e0 openresty -v
      - uses: actions/checkout@v3
        with:
          repository: asdf-vm/asdf
          path: asdf

      - uses: actions/checkout@v3
        with:
          path: asdf-openresty

      - name: Setup upterm session
        uses: lhotari/action-upterm@v1

      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v1
        with:
          command: openresty -v

    # - name: Bump version and push tag
    #   id: tag_version
    #   uses: mathieudutour/github-tag-action@v6.0
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     dry_run: true
