name: Lint

# on:
#   push:
#     branches:
#       - main
on: push

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    container:
      image: koalaman/shellcheck
      volumes:
        - $(pwd):/mnt
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log the node version
        run: |
          shellcheck --external-sources --shell bash bin/* lib/**/*.bash
